"""create booking schema

Revision ID: bad59298ca5e
Revises: 
Create Date: 2026-04-26 12:26:02.846225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad59298ca5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invitation_statuses',
    sa.Column('invitation_status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('invitation_status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reservation_statuses',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('name')
    )
    reservation_statuses_table = sa.table(
        'reservation_statuses',
        sa.column('status_id', sa.Integer),
        sa.column('name', sa.String),
    )
    op.bulk_insert(
        reservation_statuses_table,
        [
            {'status_id': 1, 'name': 'Подтверждено'},
            {'status_id': 2, 'name': 'Изменено'},
            {'status_id': 3, 'name': 'Отменено'},
            {'status_id': 4, 'name': 'Завершено'},
        ],
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    invitation_statuses_table = sa.table(
        'invitation_statuses',
        sa.column('invitation_status_id', sa.Integer),
        sa.column('name', sa.String),
    )
    op.bulk_insert(
        invitation_statuses_table,
        [
            {'invitation_status_id': 1, 'name': 'Ожидает ответа'},
            {'invitation_status_id': 2, 'name': 'Принято'},
            {'invitation_status_id': 3, 'name': 'Отклонено'},
        ],
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('equipment',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['equipment_types.type_id'], ),
    sa.PrimaryKeyConstraint('equipment_id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_datetime > start_datetime', name='ck_reservation_datetime_order'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['reservation_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index('ix_reservations_room_time', 'reservations', ['room_id', 'start_datetime', 'end_datetime'], unique=False)
    op.create_table('participants',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invitation_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_status_id'], ['invitation_statuses.invitation_status_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_id'),
    sa.UniqueConstraint('reservation_id', 'user_id', name='uq_participant_user')
    )
    op.create_table('reservation_equipment',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', 'equipment_id'),
    sa.UniqueConstraint('reservation_id', 'equipment_id', name='uq_reservation_equipment_pair')
    )
    op.create_table('room_equipment',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'equipment_id'),
    sa.UniqueConstraint('room_id', 'equipment_id', name='uq_room_equipment_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_equipment')
    op.drop_table('reservation_equipment')
    op.drop_table('participants')
    op.drop_index('ix_reservations_room_time', table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('equipment')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('reservation_statuses')
    op.drop_table('invitation_statuses')
    op.drop_table('equipment_types')
    # ### end Alembic commands ###
